version: '3.8'
services:
  app:
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://user:pass@localhost:5432/gdpr_db
      - REDIS_URL=redis://localhost:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend_templates/nextjs_base
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend_templates/nextjs_base:/app
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: gdpr_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.template:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
