version: '3.8'
services:
  app:
    build: .
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://user:pass@localhost:5432/gdpr_db
      - REDIS_URL=redis://localhost:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: gdpr_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
